export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const VALIDAR_FORMULARIO_EXITO = "VALIDAR_FORMULARIO_EXITO";
export const VALIDAR_FORMULARIO_ERROR = "VALIDAR_FORMULARIO_ERROR";

export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_LISTADO_PRODUCTOS = "COMENZAR_LISTADO_PRODUCTOS";
export const LISTADO_PRODUCTOS_EXITOSA = "LISTADO_PRODUCTOS_EXITOSA";
export const LISTADO_PRODUCTOS_ERROR = "LISTADO_PRODUCTOS_ERROR";

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR'
export const PRODUCTO_ELIMINADO_EXITOSO = 'PRODUCTO_ELIMINADO_EXITOSO'
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR'